### Create New Product
POST http://localhost:8080/products/post
Accept: application/json
Content-Type: application/json

{
  "name": "Mackbook",
  "description": "Tahan banting"
}

### Get All Products
GET http://localhost:8080/products
Accept: application/json

### Get Product By Id
GET http://localhost:8080/products/3bb46fa0-cdcf-40fd-9171-f3679c2191ab
Accept: application/json


### Update Product
PUT http://localhost:8080/products
Accept: application/json
Content-Type: application/json

{
  "id": "465540ec-e103-4add-aabf-1706b980a87f",
  "name": "Mackbook",
  "description": "Tahan banting oyy"
}
### Delete Product
DELETE http://localhost:8080/products/
Content-Type: application/json







